from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Currency Calculator")
        MainWindow.resize(616, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setStyleSheet("QComboBox QAbstractItemView {\n"
"    max-height: 300px; /* Açılır listenin yüksekliğini sınırlayın */\n"
"    width: 300px;      /* Genişliği ayarlayın (isteğe bağlı) */\n"
"}\n"
"")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setMaxVisibleItems(5)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setStyleSheet("QComboBox QAbstractItemView {\n"
"    max-height: 300px; /* Açılır listenin yüksekliğini sınırlayın */\n"
"    width: 300px;      /* Genişliği ayarlayın (isteğe bağlı) */\n"
"}\n"
"")
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setMaxVisibleItems(5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("1")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(25)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setStyleSheet("QComboBox QAbstractItemView {\n"
"    max-height: 300px; /* Açılır listenin yüksekliğini sınırlayın */\n"
"    width: 300px;      /* Genişliği ayarlayın (isteğe bağlı) */\n"
"}\n"
"")
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setMaxVisibleItems(5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_5)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(46)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout_2.addWidget(self.tableWidget, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuTheme = QtWidgets.QMenu(self.menuSettings)
        self.menuTheme.setObjectName("menuTheme")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDark_Theme = QtWidgets.QAction(MainWindow)
        self.actionDark_Theme.setObjectName("actionDark_Theme")
        self.actionDefault_Theme = QtWidgets.QAction(MainWindow)
        self.actionDefault_Theme.setObjectName("actionDefault_Theme")
        self.actionFixer_io = QtWidgets.QAction(MainWindow)
        self.actionFixer_io.setObjectName("actionFixer_io")
        self.actionAPI = QtWidgets.QAction(MainWindow)
        self.actionAPI.setObjectName("actionAPI")
        self.actionDevrim_Tun_er = QtWidgets.QAction(MainWindow)
        self.actionDevrim_Tun_er.setObjectName("actionDevrim_Tun_er")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.menuTheme.addAction(self.actionDark_Theme)
        self.menuTheme.addAction(self.actionDefault_Theme)
        self.menuSettings.addAction(self.menuTheme.menuAction())
        self.menuAbout.addAction(self.actionDevrim_Tun_er)
        self.menuAbout.addAction(self.actionGithub)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FROM : "))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "JPY"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "GBP"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "AUD"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "CAD"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "CHF"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "CNY"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "HKD"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "NZD"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "SEK"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "KRW"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "SGD"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "NOK"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "MXN"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "INR"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "RUB"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "ZAR"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "TRY"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "BRL"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "TWD"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "DKK"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "PLN"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "THB"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "IDR"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "HUF"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "CZK"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "ILS"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "CLP"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "PHP"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "AED"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "SAR"))
        self.comboBox_4.setItemText(32, _translate("MainWindow", "MYR"))
        self.comboBox_4.setItemText(33, _translate("MainWindow", "ARS"))
        self.comboBox_4.setItemText(34, _translate("MainWindow", "COP"))
        self.comboBox_4.setItemText(35, _translate("MainWindow", "PEN"))
        self.comboBox_4.setItemText(36, _translate("MainWindow", "VND"))
        self.comboBox_4.setItemText(37, _translate("MainWindow", "NGN"))
        self.comboBox_4.setItemText(38, _translate("MainWindow", "EGP"))
        self.comboBox_4.setItemText(39, _translate("MainWindow", "PKR"))
        self.comboBox_4.setItemText(40, _translate("MainWindow", "UAH"))
        self.comboBox_4.setItemText(41, _translate("MainWindow", "KWD"))
        self.comboBox_4.setItemText(42, _translate("MainWindow", "BDT"))
        self.comboBox_4.setItemText(43, _translate("MainWindow", "QAR"))
        self.comboBox_4.setItemText(44, _translate("MainWindow", "OMR"))
        self.comboBox_4.setItemText(45, _translate("MainWindow", "MAD"))
        self.comboBox_4.setItemText(46, _translate("MainWindow", "RON"))
        self.comboBox_4.setItemText(47, _translate("MainWindow", "BGN"))
        self.comboBox_4.setItemText(48, _translate("MainWindow", "DZD"))
        self.comboBox_4.setItemText(49, _translate("MainWindow", "JOD"))
        self.pushButton_4.setText(_translate("MainWindow", "Update API"))
        self.label_2.setText(_translate("MainWindow", "TO : "))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "JPY"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "GBP"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "AUD"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "CAD"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "CHF"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "CNY"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "HKD"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "NZD"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "SEK"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "KRW"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "SGD"))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "NOK"))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "MXN"))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "INR"))
        self.comboBox_6.setItemText(16, _translate("MainWindow", "RUB"))
        self.comboBox_6.setItemText(17, _translate("MainWindow", "ZAR"))
        self.comboBox_6.setItemText(18, _translate("MainWindow", "TRY"))
        self.comboBox_6.setItemText(19, _translate("MainWindow", "BRL"))
        self.comboBox_6.setItemText(20, _translate("MainWindow", "TWD"))
        self.comboBox_6.setItemText(21, _translate("MainWindow", "DKK"))
        self.comboBox_6.setItemText(22, _translate("MainWindow", "PLN"))
        self.comboBox_6.setItemText(23, _translate("MainWindow", "THB"))
        self.comboBox_6.setItemText(24, _translate("MainWindow", "IDR"))
        self.comboBox_6.setItemText(25, _translate("MainWindow", "HUF"))
        self.comboBox_6.setItemText(26, _translate("MainWindow", "CZK"))
        self.comboBox_6.setItemText(27, _translate("MainWindow", "ILS"))
        self.comboBox_6.setItemText(28, _translate("MainWindow", "CLP"))
        self.comboBox_6.setItemText(29, _translate("MainWindow", "PHP"))
        self.comboBox_6.setItemText(30, _translate("MainWindow", "AED"))
        self.comboBox_6.setItemText(31, _translate("MainWindow", "SAR"))
        self.comboBox_6.setItemText(32, _translate("MainWindow", "MYR"))
        self.comboBox_6.setItemText(33, _translate("MainWindow", "ARS"))
        self.comboBox_6.setItemText(34, _translate("MainWindow", "COP"))
        self.comboBox_6.setItemText(35, _translate("MainWindow", "PEN"))
        self.comboBox_6.setItemText(36, _translate("MainWindow", "VND"))
        self.comboBox_6.setItemText(37, _translate("MainWindow", "NGN"))
        self.comboBox_6.setItemText(38, _translate("MainWindow", "EGP"))
        self.comboBox_6.setItemText(39, _translate("MainWindow", "PKR"))
        self.comboBox_6.setItemText(40, _translate("MainWindow", "UAH"))
        self.comboBox_6.setItemText(41, _translate("MainWindow", "KWD"))
        self.comboBox_6.setItemText(42, _translate("MainWindow", "BDT"))
        self.comboBox_6.setItemText(43, _translate("MainWindow", "QAR"))
        self.comboBox_6.setItemText(44, _translate("MainWindow", "OMR"))
        self.comboBox_6.setItemText(45, _translate("MainWindow", "MAD"))
        self.comboBox_6.setItemText(46, _translate("MainWindow", "RON"))
        self.comboBox_6.setItemText(47, _translate("MainWindow", "BGN"))
        self.comboBox_6.setItemText(48, _translate("MainWindow", "DZD"))
        self.comboBox_6.setItemText(49, _translate("MainWindow", "JOD"))
        self.pushButton_3.setText(_translate("MainWindow", "Currency Swap"))
        self.label_3.setText(_translate("MainWindow", "AMOUNT : "))
        self.pushButton_8.setText(_translate("MainWindow", "Calculate"))
        self.label_5.setText(_translate("MainWindow", "TOTAL :"))
        self.label_4.setText(_translate("MainWindow", "1.1123"))
        self.pushButton_2.setText(_translate("MainWindow", "Copy Total"))
        self.pushButton.setText(_translate("MainWindow", "DOWNLOAD HISTORY"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "25."))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "24."))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "23."))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "22."))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "21."))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "20."))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "19."))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "18."))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "17."))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "16."))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "15."))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "14."))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13."))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "12."))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "11."))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "10."))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "9."))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "8."))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "7."))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "6."))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "5."))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "4."))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "3."))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "2."))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "1."))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AMOUNT"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FROM"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TO"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TOTAL"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DATE"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "HOUR"))
        self.pushButton_5.setText(_translate("MainWindow", "Fixer.io"))
        self.label_6.setText(_translate("MainWindow", "API : "))
        self.label_7.setText(_translate("MainWindow", "Failed"))
        self.pushButton_7.setText(_translate("MainWindow", "Reset"))
        self.pushButton_6.setText(_translate("MainWindow", "Log in"))
        self.label_8.setText(_translate("MainWindow", "NOTES "))
        self.pushButton_9.setText(_translate("MainWindow", "CLEAR"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "TRY"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "USD"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "EUR"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "JPY"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "GBP"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "AUD"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "CAD"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "CHF"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "CNY"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "HKD"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "NZD"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "SEK"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "KRW"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "SGD"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "NOK"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "MXN"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "INR"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "RUB"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "ZAR"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "BRL"))
        self.comboBox_5.setItemText(20, _translate("MainWindow", "TWD"))
        self.comboBox_5.setItemText(21, _translate("MainWindow", "DKK"))
        self.comboBox_5.setItemText(22, _translate("MainWindow", "PLN"))
        self.comboBox_5.setItemText(23, _translate("MainWindow", "THB"))
        self.comboBox_5.setItemText(24, _translate("MainWindow", "IDR"))
        self.comboBox_5.setItemText(25, _translate("MainWindow", "HUF"))
        self.comboBox_5.setItemText(26, _translate("MainWindow", "CZK"))
        self.comboBox_5.setItemText(27, _translate("MainWindow", "ILS"))
        self.comboBox_5.setItemText(28, _translate("MainWindow", "CLP"))
        self.comboBox_5.setItemText(29, _translate("MainWindow", "PHP"))
        self.comboBox_5.setItemText(30, _translate("MainWindow", "AED"))
        self.comboBox_5.setItemText(31, _translate("MainWindow", "SAR"))
        self.comboBox_5.setItemText(32, _translate("MainWindow", "MYR"))
        self.comboBox_5.setItemText(33, _translate("MainWindow", "ARS"))
        self.comboBox_5.setItemText(34, _translate("MainWindow", "COP"))
        self.comboBox_5.setItemText(35, _translate("MainWindow", "PEN"))
        self.comboBox_5.setItemText(36, _translate("MainWindow", "VND"))
        self.comboBox_5.setItemText(37, _translate("MainWindow", "NGN"))
        self.comboBox_5.setItemText(38, _translate("MainWindow", "EGP"))
        self.comboBox_5.setItemText(39, _translate("MainWindow", "PKR"))
        self.comboBox_5.setItemText(40, _translate("MainWindow", "UAH"))
        self.comboBox_5.setItemText(41, _translate("MainWindow", "KWD"))
        self.comboBox_5.setItemText(42, _translate("MainWindow", "BDT"))
        self.comboBox_5.setItemText(43, _translate("MainWindow", "QAR"))
        self.comboBox_5.setItemText(44, _translate("MainWindow", "OMR"))
        self.comboBox_5.setItemText(45, _translate("MainWindow", "MAD"))
        self.comboBox_5.setItemText(46, _translate("MainWindow", "RON"))
        self.comboBox_5.setItemText(47, _translate("MainWindow", "BGN"))
        self.comboBox_5.setItemText(48, _translate("MainWindow", "DZD"))
        self.comboBox_5.setItemText(49, _translate("MainWindow", "JOD"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "USD"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "EUR"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "TRY"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "JPY"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "GBP"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "AUD"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "CHF"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "CAD"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "CNY"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "HKD"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "NZD"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "SEK"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "KRW"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "SGD"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "MXN"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "INR"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "RUB"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "ZAR"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "BRL"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "TWD"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "DKK"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "PLN"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "THB"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "IDR"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "HUF"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "CZK"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "ILS"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "CLP"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "PHP"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "AED"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "SAR"))
        item = self.tableWidget.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "MYR"))
        item = self.tableWidget.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "ARS"))
        item = self.tableWidget.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "COP"))
        item = self.tableWidget.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "PEN"))
        item = self.tableWidget.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "VND"))
        item = self.tableWidget.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "NGN"))
        item = self.tableWidget.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "EGP"))
        item = self.tableWidget.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "PKR"))
        item = self.tableWidget.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "KWD"))
        item = self.tableWidget.verticalHeaderItem(40)
        item.setText(_translate("MainWindow", "BDT"))
        item = self.tableWidget.verticalHeaderItem(41)
        item.setText(_translate("MainWindow", "QAR"))
        item = self.tableWidget.verticalHeaderItem(42)
        item.setText(_translate("MainWindow", "OMR"))
        item = self.tableWidget.verticalHeaderItem(43)
        item.setText(_translate("MainWindow", "MAD"))
        item = self.tableWidget.verticalHeaderItem(44)
        item.setText(_translate("MainWindow", "RON"))
        item = self.tableWidget.verticalHeaderItem(45)
        item.setText(_translate("MainWindow", "BGN"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AMOUNT"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionDark_Theme.setText(_translate("MainWindow", "Dark Theme"))
        self.actionDefault_Theme.setText(_translate("MainWindow", "Default Theme"))
        self.actionFixer_io.setText(_translate("MainWindow", "Fixer.io"))
        self.actionAPI.setText(_translate("MainWindow", "API"))
        self.actionDevrim_Tun_er.setText(_translate("MainWindow", "Devrim Tunçer"))
        self.actionGithub.setText(_translate("MainWindow", "Github"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
